### ISSUE TITLE
Install script not working.

### ISSUE THREAD

**Issue by bekirk** [ocmdev/rita#1]
Line 60 of the install script fails:

[+] Transferring files
cp: cannot stat ‘bin’: No such file or directory

I have commented that out and then line 62 fails with this error:

[+] Transferring files
cp: cannot stat ‘usr’: No such file or directory

When I comment that out it seems to then succeed, but I don't know if there are missing files that need copied over.

Thank you

**Comment by lawrencehoffman** [comment]
I removed that `cp ` from the install script so that the error would not be generated. Really, we probably don't want to copy the bin file anyhow, considering that the copy would create two bins with the same name.
