### ISSUE TITLE
Recommended Upgrade Path Documentation

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#102]
We should document a recommended upgrade procedure.  The following commands should be a reasonable attempt at updating a RITA installation.

```
# This removes a dependency issue caused by a third party
rm -rf $GOPATH/src/github.com/*irupsen/logrus
echo "Updating to the latest release of RITA."
# This fetches the latest code from Github
go get -u github.com/ocmdev/rita
# This will compile the latest code and install the binary into $GOPATH/bin
cd $GOPATH/src/github.com/ocmdev/rita
make install
# Using old config files in RITA will cause issues so this updates to the newest config and backs up the old one
echo "Backing up your RITA config to ~/.rita/config.yaml-orig"
mv ~/.rita/config.yaml ~/.rita/config.yaml-orig
cp $GOPATH/src/github.com/ocmdev/rita/etc/rita.yaml ~/.rita/config.yaml
echo "RITA has been updated to:" $(rita --version)
echo "You must copy any custom settings from ~/.rita/config.yaml-orig to ~/.rita/config.yaml"
```

The `go get` is redundant from `make install` and could be replaced by changing to the directory and running `git pull`.  The one thing `go get -u` will do though is update dependencies.  This may or may not be a good thing.  We probably should look at vendoring again to decide if that's the right way to go.

**Comment by Zalgo2462** [comment]
For right now, let's not update dependencies.

https://github.com/ocmdev/rita/wiki/Upgrading-RITA
