### ISSUE TITLE
Separate internal mongo settings from config.yaml

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#103]
Can we move the Mongo table settings to a separate configuration file (e.g. ~/.rita/database-structure.yaml)?  This is more of an open question/discussion that needs to be decided before implementing.

```
# NOTE: DO NOT CHANGE THE SETTINGS BELOW UNLESS YOU ARE FAMILIAR WITH THE CODE #
Structure:
    ConnectionTable: conn
    HttpTable: http
    DnsTable: dns
    UniqueConnectionTable: uconn
    HostTable: host

BlackListed:
    ThreadCount: 2
    ChannelSize: 1000
    BlackListTable: blacklisted
    Database: rita-blacklist

Dns:
    ExplodedDnsTable: explodedDns
    HostnamesTable: hostnames

Crossref:
    InternalTable: internXREF
    ExternalTable: externXREF
    BeaconThreshold: .7

Scanning:
    ScanThreshold: 50
    ScanTable: scan

Beacon:
    DefaultConnectionThresh: 24
    BeaconTable: beacon

Urls:
    UrlsTable: urls

UserAgent:
    UserAgentTable: useragent

MetaTables:
    FilesTable: files
    DatabasesTable: databases


# Adjusting batchsize and prefetch may help speed up certain database queries
BatchSize: 300
Prefetch: 0.33
```

This would allow the following improvements:

* When RITA code updates that adds or changes these fields, using an old config will cause errors.  However, this means the user needs to update their config file and possibly either overwrite their modifications or manually copy them over.  Having a separate file would allow changes to database structure without forcing users to update their config.
* This would declutter the user's config file and make it less confusing to edit.

**Comment by Zalgo2462** [comment]
This will be easier to implement once the TLS and RITA-BL changes go through since they both alter the configuration file.

**Comment by ethack** [comment]
Additionally, we should consider versioning config files and having rita automatically detect older configs and give the user a more useful error message.

**Comment by Zalgo2462** [comment]
Thats not a bad thought. However, I'd like to get a proposal put together for that feature as that sounds like rat's nest of a feature to support (off the top of my head).

Should get in a PR for this issue by the end of day.
