### ISSUE TITLE
RITA does not support TLS encryption / MongoDB authentication

### ISSUE THREAD

**Issue by ocmdev** [ocmdev/rita#105]
RITA should be able to communicate with MongoDB over encrypted channels, and properly authenticate to MongoDB. Note: this should be an optional configuration option.

**Comment by Zalgo2462** [comment]
Since the blacklist backend must support TLS, and rita-blacklist has been replaced by rita-bl, it is imperative that we merge in the rita-bl module soon. Rita-bl already contains this functionality.

**Comment by Zalgo2462** [comment]
Code is here: https://github.com/Zalgo2462/rita/tree/tls
Waiting on: https://github.com/ocmdev/rita/pull/100
