### ISSUE TITLE
Is DirectoryMap required?

### ISSUE THREAD

**Issue by gymzombie** [ocmdev/rita#110]
I'm doing a first time setup, and the "Importing Data, Option 2" section says _"Say you have two sets of logs to analyze"_  

What if you don't? Can I comment the DirectoryMap entries, or should I put one entry and comment the other?

**Comment by ethack** [comment]
You can just have one entry in `DirectoryMap`.  

But `DirectoryMap` is strictly optional.  I believe you can set `DefaultDatabase` and anything not matched in `DirectoryMap` will be sent there.

**Comment by gymzombie** [comment]
Helpful. Thanks for responding!
