### ISSUE TITLE
Support --config option universally

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#115]
Is there already a way to use custom config files across all commands?

These commands do not seem to support the `-c, --config` option to specify a custom config file.
* delete-database
* reset-analysis
* all the show-* commands

My use case is that I have different metadatabases specified in different config files and cannot work with both without changing ~/.rita/config.yaml.  So while I have a shell script running multiple long-running rita commands in a different terminal I cannot even use show-* commands on other databases without risking messing up the config for the shell script.

Alternatively or additionally, an environment variable could be checked for the location of the config file.

**Comment by Zalgo2462** [comment]
This was an undocumented fix in the dev branch. See https://github.com/ocmdev/rita/pull/99/files

**Comment by ethack** [comment]
You're right! I even read and commented on that pull request. Sheesh my memory is bad.
