### ISSUE TITLE
Panic when running analyze

### ISSUE THREAD

**Issue by lmshiry** [ocmdev/rita#125]
Hi,

I managed to get bro, mongodb, go, rita installed onto my dedicated network monitoring box.  It is running Oracle Linux 7.3.  I know rita was pretty much built for ubuntu but not an option here.  As far as I can tell all the components are working ok, until I tell rita to analyze the newly imported data from bro.  See output below.  Are there any gotchas when not running on ubuntu?

rita version v1.0.0-alpha2-2-g37240cb

Hardware is fairly stout, 64GB RAM, 16/32 cores @ 2.6GHz

rita import
[+] Importing /var/log/bro/
	[-] Finding files to parse
	[-] Parsing /var/log/bro/2017-07-12/dns.15:00:00-16:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.19:00:00-20:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.13:59:18-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.14:00:00-15:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.15:00:00-16:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.21:00:00-22:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.23:00:00-00:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.22:00:00-23:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.20:00:00-21:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.13:55:27-13:58:05.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.13:59:13-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.13:55:22-13:58:05.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.17:00:00-18:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.18:00:00-19:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/conn.16:00:00-17:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.14:00:00-15:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.17:00:00-18:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.17:00:00-18:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.16:00:00-17:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.16:00:00-17:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.09:00:00-10:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.08:00:00-09:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.21:00:00-22:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.11:13:42-11:15:45.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.02:00:00-03:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.15:00:00-16:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.19:00:00-20:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.11:00:00-11:13:06.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.20:00:00-21:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.18:00:00-19:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.11:13:18-11:13:24.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.07:00:00-08:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.01:00:00-02:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.14:00:00-15:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.10:00:00-11:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.20:00:00-21:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.11:42:07-11:54:35.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.06:00:00-07:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.19:00:00-20:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.11:00:00-11:42:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.11:42:02-11:54:35.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.11:42:04-11:54:35.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.00:00:00-01:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.13:00:00-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.05:00:00-06:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.18:00:00-19:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.10:00:00-11:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.15:00:00-16:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.13:55:23-13:58:05.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.04:00:00-05:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.23:00:00-00:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.07:00:00-08:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.03:00:00-04:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.22:00:00-23:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.21:00:00-22:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.21:00:00-22:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.02:00:00-03:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.01:00:00-02:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.22:00:00-23:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.11:00:00-11:42:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.11:00:00-11:42:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.13:59:14-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.05:00:00-06:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.19:00:00-20:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.20:00:00-21:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.23:00:00-00:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.00:00:00-01:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.12:00:00-13:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.14:00:00-15:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.06:00:00-07:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/dns.18:00:00-19:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-12/http.22:00:00-23:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.11:15:53-12:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.16:00:00-17:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.23:00:00-00:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.20:00:00-21:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.15:00:00-16:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.10:00:00-11:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.14:00:00-15:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.10:00:00-11:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.18:00:00-19:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.13:00:00-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.11:13:38-11:15:45.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.02:00:00-03:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.15:00:00-16:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.07:00:00-08:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.19:00:00-20:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.11:15:47-12:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.03:00:00-04:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.16:00:00-17:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.08:00:00-09:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.03:00:00-04:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.04:00:00-05:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.12:00:00-13:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.16:00:00-17:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.17:00:00-18:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.11:13:13-11:13:24.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.01:00:00-02:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.14:00:00-15:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.06:00:00-07:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.09:00:00-10:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.04:00:00-05:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.08:00:00-09:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.17:00:00-18:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.09:00:00-10:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.21:00:00-22:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.22:00:00-23:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.11:54:42-12:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.12:00:00-13:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.11:54:37-12:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.11:54:37-12:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.10:00:00-11:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.08:00:00-09:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.07:00:00-08:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.21:00:00-22:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.20:00:00-21:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.07:00:00-08:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.11:00:00-11:13:06.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.11:13:13-11:13:24.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.01:00:00-02:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.11:13:39-11:15:45.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.02:00:00-03:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.00:00:00-01:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.23:00:00-00:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.13:00:00-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.07:00:00-08:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.06:00:00-07:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.12:00:00-13:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.19:00:00-20:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.05:00:00-06:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.11:00:00-11:13:06.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.00:00:00-01:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.04:00:00-05:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.08:00:00-09:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.05:00:00-06:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.08:00:00-09:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.18:00:00-19:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.10:00:00-11:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.23:00:00-00:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.13:00:00-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.06:00:00-07:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.06:00:00-07:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.12:00:00-13:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.09:00:00-10:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.01:00:00-02:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.02:00:00-03:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.12:00:00-13:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.09:00:00-10:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.01:00:00-02:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.02:00:00-03:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.05:00:00-06:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.00:00:00-01:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.05:00:00-06:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.00:00:00-01:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.13:00:00-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.13:00:00-14:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/conn.17:00:00-18:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.09:00:00-10:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/dns.22:00:00-23:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-13/http.11:15:49-12:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/conn.03:00:00-04:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.04:00:00-05:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.04:00:00-05:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/dns.03:00:00-04:00:00.log.gz -> Bro
	[-] Parsing /var/log/bro/2017-07-14/http.03:00:00-04:00:00.log.gz -> Bro
	[-] Indexing log entries. This may take a while.

rita analyze
[+] Analyzing:
	[-] Bro
[+] Analyzing Bro
	[-] Running Unique Connections Analysis
	[-] Running Unique Hosts Analysis
panic: (*logrus.Entry) (0x9698c0,0xc42007ba40)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc42007b220, 0xc420139c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/sirupsen/logrus/entry.go:124 +0x33e
github.com/sirupsen/logrus.(*Entry).Panic(0xc42007b9f0, 0xc4202292f0, 0x1, 0x1)
	/root/go/src/github.com/sirupsen/logrus/entry.go:169 +0x127
github.com/ocmdev/rita/database.(*DB).AggregateCollection(0xc42017d640, 0xc420136c40, 0x4, 0xc420236340, 0xc4201f8a80, 0x5, 0x5, 0x0)
	/root/go/src/github.com/ocmdev/rita/database/control.go:116 +0x43c
github.com/ocmdev/rita/analysis/structure.BuildHostsCollection(0xc42017d660)
	/root/go/src/github.com/ocmdev/rita/analysis/structure/hosts.go:30 +0x2c5
github.com/ocmdev/rita/commands.logAnalysisFunc(0xc42021eb20, 0x15, 0xc420198a15, 0x3, 0xc42017d660, 0x99a9a8)
	/root/go/src/github.com/ocmdev/rita/commands/analyze.go:135 +0x46d
github.com/ocmdev/rita/commands.analyze(0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/ocmdev/rita/commands/analyze.go:84 +0xad8
github.com/ocmdev/rita/commands.init.1.func1(0xc4200a91e0, 0x0, 0xc4200a91e0)
	/root/go/src/github.com/ocmdev/rita/commands/analyze.go:30 +0xa7
github.com/urfave/cli.HandleAction(0x8d2d40, 0x99a9d0, 0xc4200a91e0, 0xc420092900, 0x0)
	/root/go/src/github.com/urfave/cli/app.go:490 +0xd4
github.com/urfave/cli.Command.Run(0x97aaf0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9969f2, 0x51, 0x0, ...)
	/root/go/src/github.com/urfave/cli/command.go:210 +0xb6e
github.com/urfave/cli.(*App).Run(0xc4200b6d00, 0xc42000c2a0, 0x2, 0x2, 0x0, 0x0)
	/root/go/src/github.com/urfave/cli/app.go:255 +0x76f
main.main()
	/root/go/src/github.com/ocmdev/rita/rita.go:26 +0x110

**Comment by Zalgo2462** [comment]
Hello, thank you for taking the time to file a bug report. Will you please attach the folder at ~/.rita/logs/[time of the incident]. I believe there should be a panic log inside of that directory.

Additionally, will you please run rita test-config and post the output?

Finally, will you please post your rita configuration file? Remember to censor your google api key.
Thank you!

**Comment by lmshiry** [comment]
I don't see a panic log, but attaching the logs from the time of the incident.  The import was at 14:34, the analyze at 14:39.
[Archive.zip](https://github.com/ocmdev/rita/files/1149578/Archive.zip)

rita test-config

BatchSize: 300
DatabaseHost: localhost:27017
Prefetch: 0.33
LogConfig:
  LogLevel: 2
  RitaLogPath: /root/.rita/logs
  LogToFile: true
  RitaLogTable: logs
  LogToDB: true
BlackListed:
  ThreadCount: 2
  ChannelSize: 1000
  BlackListTable: blacklisted
  Database: rita-blacklist
Dns:
  ExplodedDnsTable: explodedDns
  HostnamesTable: hostnames
Crossref:
  InternalTable: internXREF
  ExternalTable: externXREF
  BeaconThreshold: 0.7
Scanning:
  ScanThreshold: 50
  ScanTable: scan
Structure:
  ConnectionTable: conn
  HttpTable: http
  DnsTable: dns
  UniqueConnectionTable: uconn
  HostTable: host
Beacon:
  DefaultConnectionThresh: 24
  BeaconTable: beacon
Urls:
  UrlsTable: urls
UserAgent:
  UserAgentTable: useragent
Bro:
  LogPath: /var/log/bro/
  DBPrefix: ""
  MetaDB: MetaDatabase
  DirectoryMap:
    UniqueDir: SeparateDatabaseName
    UniqueDir2: SeparateDatabaseName2
  DefaultDatabase: Bro
  UseDates: false
  ImportBuffer: 100000
SafeBrowsing:
  APIKey: ""
  Database: /root/.rita/safebrowsing
MetaTables:
  FilesTable: files
  DatabasesTable: databases
version: v1.0.0-alpha2-2-g37240cb



 cat config.yaml 
# Mongo Database to connect to
DatabaseHost: localhost:27017

LogConfig:
    # LogLevel
    # 3 = debug
    # 2 = info
    # 1 = warn
    # 0 = error
    LogLevel: 2

    # LogPath is the path for Rita's logs, generally this just defaults to
    # $HOME/.rita/logs. Logs will only be written here if LogToFile is true
    RitaLogPath: $HOME/.rita/logs
    LogToFile: true

    RitaLogTable: logs
    LogToDB: true

# The section Bro configures the bro ingestor
Bro:
    # Path to a top level directory of log files
    LogPath: /var/log/bro/

    # All databases in this test will get prefixed with the database prefix
    #DBPrefix: PrefixForDatabase

    # Subdirectories of LogPath may be separated into different databases for the
    # test. Map each directory to the database you wish that directory to wind up
    # in. This is good for running tests against multiple subnets and network
    # segments. Put the directory name on the left side of the colon, and the
    # database you wish the logs from that directory to go in on the right side.
    DirectoryMap:
        UniqueDir: SeparateDatabaseName
        UniqueDir2: SeparateDatabaseName2

    # If set, files which don't match the directory map will be placed
    # in this default database.
    DefaultDatabase: Bro

    # There needs to be one metadatabase per test. This database holds information
    # about the test and the files related to the test. If there are several
    # subnets mapped in DirectoryMap each will be handled separately and that
    # separation is handled by the metadatabase.
    MetaDB: MetaDatabase

    # If use dates is true the logs will be split into databases by date, this is
    # best for if you have multiple days worth of log files in the logpath and wish
    # to treat each day as a separate test. 24hours worth of data is the ideal for
    # analysis, and using dates will ensure that tests are broken into 24hour periods
    # around midnight of each day.
    UseDates: false

    # The number of records shipped off to MongoDB at a time. Increasing
    # the size of the buffer will improve import timings but will leave more
    # records unimported if there is an error
    ImportBuffer: 100000

SafeBrowsing:
    APIKey: ""
    Database: $HOME/.rita/safebrowsing

# NOTE: DO NOT CHANGE THE SETTINGS BELOW UNLESS YOU ARE FAMILIAR WITH THE CODE #
Structure:
    ConnectionTable: conn
    HttpTable: http
    DnsTable: dns
    UniqueConnectionTable: uconn
    HostTable: host

BlackListed:
    ThreadCount: 2
    ChannelSize: 1000
    BlackListTable: blacklisted
    Database: rita-blacklist

Dns:
    ExplodedDnsTable: explodedDns
    HostnamesTable: hostnames

Crossref:
    InternalTable: internXREF
    ExternalTable: externXREF
    BeaconThreshold: .7

Scanning:
    ScanThreshold: 50
    ScanTable: scan

Beacon:
    DefaultConnectionThresh: 24
    BeaconTable: beacon

Urls:
    UrlsTable: urls

UserAgent:
    UserAgentTable: useragent

MetaTables:
    FilesTable: files
    DatabasesTable: databases


# Adjusting batchsize and prefetch may help speed up certain database queries
BatchSize: 300
Prefetch: 0.33

**Comment by Zalgo2462** [comment]
Thank you very much. 
Can you please run `mongoexport --db MetaDatabase --collection logs | gzip > logs.json.gz` and attach the resulting file. 

The file logger in the master branch did not catch the panic. However, the database logger should have.

**Comment by lmshiry** [comment]
OK I see the error in there:
{ "_id" : { "$oid" : "59690ff694be36e67bfa95db" }, "error" : "exception: disallowed field type Array in object expression (at 'hosts')", "Level" : 0, "Time" : { "$date" : "2017-07-14T14:39:50.680-0400" }, "Message" : "Failed aggregate operation" }

File attached.
[logs.json.gz](https://github.com/ocmdev/rita/files/1150324/logs.json.gz)

**Comment by Zalgo2462** [comment]
Thanks!
What is the output of 'mongod --version'

**Comment by lmshiry** [comment]
mongod --version
db version v2.6.12
2017-07-16T10:46:02.821-0400 git version: nogitversion
2017-07-16T10:46:02.821-0400 OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by Zalgo2462** [comment]
RITA requires MongoDB 3.2 or newer. The issue you are having is due to a schema change MongoDB made between the 2.x and 3.x aggregation frameworks.

**Comment by lmshiry** [comment]
That was it, reinstalled to mongodb v3.4.6 and it seems to work great now.  Thanks very much for your help!
