### ISSUE TITLE
RITA Incorrectly Gathers Which Hosts Connected to a URL

### ISSUE THREAD

**Issue by Zalgo2462** [ocmdev/rita#129]
Currently, the blacklisted url module will gather any host that connected to the server hosting a blacklisted url when trying to determine which hosts reached the given blacklisted url.

Additionally, RITA cannot currently report which hosts contacted a long or most visited url.

A solution is to use a small aggregation on each url. Match on the host and resource, group the results and add the source ip addresses to a set, and unwind the set.

**Comment by ethack** [comment]
Closed with https://github.com/ocmdev/rita/pull/136
