### ISSUE TITLE
install.sh mongodb repository error

### ISSUE THREAD

**Issue by xaled** [ocmdev/rita#142]
Greetings,

When running RITA install script:  `install.sh`, and when it tries to install mongodb, the script fails with this error:

`E: The repository 'http://repo.mongodb.org/apt/ubuntu zesty/mongodb-org/3.4 Release' does not have a Release file.`

Apparently this repository is no longer valid.
So, I've fixed it by changing the repository in  install.sh from:

`	
echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/3.4 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.4.list
`
to:

`	
echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.4 main" > /etc/apt/sources.list.d/mongodb-org-3.4.list
`

**Comment by Zalgo2462** [comment]
Thank you for your bug report. It seems mongo has moved to only support ubuntu LTS release. We will look at our options for dealing with this in the install script. In the mean time, I suggest you use the package from xenial rather than wheezy as it is newer.

**Comment by xaled** [comment]
Yes xenial repository should be better.
