### ISSUE TITLE
Patch install script to support CentOS/Redhat

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#144]
We received a contribution via email.  This modified install script "supports both ubuntu 16.x and centos 7/redhat 7 as install targets.  By breaking out the ubuntu-isms into their own functions, it will more easily be extended to other linux flavors in the future if needed."

We need to review and put in a proper pull request.  Also, we should discuss what this would mean for adding official support for other OS's.

[install.txt](https://github.com/ocmdev/rita/files/1347737/install.txt)

**Comment by Zalgo2462** [comment]
The install script has changed since this had been submitted. I will work on integrating this. CentOS 7 should be easier to support since it has systemd.
