### ISSUE TITLE
Fix the UseDates Functionality in RITA

### ISSUE THREAD

**Issue by Zalgo2462** [ocmdev/rita#176]
The UseDates functionality may cause a crash when importing data. Bro writes a log entry out when a connection ends. This means that under the UseDates option, RITA may attempt to write data to a database which may have already been analyzed. Under the master branch, this causes a crash. I do not believe this causes a crash in the dev branch.

**Comment by ethack** [comment]
Possible alternatives to replace the ability to automate running of RITA:

* Run something like the following command in a cron script. `rita import -i /opt/bro/logs/$(date +%Y-%m-%d) -d $(date +%Y-%m-%d) && rita analyze`
* Remove/replace/modify the DirectoryMap option. Instead of having to manually specify directories, automatically create a new database for each subdirectory of LogPath.

**Comment by Zalgo2462** [comment]
I can't find a way to make bro create the date folders when parsing a pcap. Unfortunately,. the date folders are created due to bro's rotate functionality (which fires when capturing live). So, removing the UseDates option would prevent splitting datasets captured outside of bro.

The dev branch shouldn't choke when the UseDates option tries to send a record into an analyzed dataset (master will).

If we stop the directory parser from following symlinks, we can stop the parser from following the current symlink. This way a user can set up their directory map with /usr/local/bro/logs. However, the UseDates issue will persist. Alternatively, we can remove the directory map.

**Comment by Zalgo2462** [comment]
Idea: remove the directory map. Allow imports of any old directory using the command line options. Add an option to the config for a bro log folder which expects the directory structure of a standard bro install. I.e. date labelled subfolders. From there, follow suggestion #2 from @ethack.

**Comment by Zalgo2462** [comment]
In reference to the scripting solution, adding the following to the crontab should work:

`15 0 * * * rita import -i $BRO_LOG_PATH/$(date -d '-1 day' '+%Y-%m-%d') -d MyDataSet-$(date -d '-1 day' '+%Y-%m-%d')`

**Comment by Zalgo2462** [comment]
I've implemented my idea regarding removing the directory map and cleaning up the cli. Check it out here: https://github.com/ocmdev/rita/pull/178 and https://github.com/Zalgo2462/rita/tree/use-dates-fix

**Comment by ethack** [comment]
Closed by https://github.com/ocmdev/rita/pull/178
