### ISSUE TITLE
Install script not working.

### ISSUE THREAD

**Issue by bekirk** [ocmdev/rita#2]
This line is also causing an error, is it too not needed?  

What is suppose to be in the usr folder?

        cp -r usr $_RITADIR/usr

```
rita$ sudo ./install.sh
[sudo] password for rita:

 _ \ _ _| __ __|  \
   /   |     |   _ \
_|_\ ___|   _| _/  _\

Brought to you by the Offensive CounterMeasures

[+] Transferring files
cp: cannot stat ‘usr’: No such file or directory

```

Thank you,
Brian

**Comment by lawrencehoffman** [comment]
Sorry about that, I moved all of the stuff under rita/usr/ into another branch to work on the front end. Which of course broke the installer. Should be good to go now.
