### ISSUE TITLE
Add option to dump results to HTML

### ISSUE THREAD

**Issue by joelillo** [ocmdev/rita#20]
Update commands like ["show beacons"](https://github.com/ocmdev/rita/blob/master/commands/show-beacons.go) to allow the user to dump results into static HTML files. (No web server... just static files.)

**Comment by ethack** [comment]
Closing for now as this isn't on the radar.

**Comment by ethack** [comment]
Reopening as John would like to use this feature for his class.

**Comment by ethack** [comment]
The resulting html page should be greppable.  This means that each row in the table should be on one line in the html.  

Here's an example of what a user might want to do.  To filter out broadcast addresses from the output, a user could run this command `grep -v '255.255.255.255' input.html > output.html` which would remove all lines with the string '255.255.255.255' and it's important that the resulting html is still valid and displays properly.

**Comment by ethack** [comment]
@bglebrun can you output the results into a basic HTML table?  Essentially, replace each beginning of line with `<tr><td>`, each comma with `</td><td>`, and each end of line with `</td></tr>`.

So an example would look like this:
```data1, data2, data3```
```<tr><td>data1</td><td>data2</td><td>data3</td><tr>```

**Comment by ethack** [comment]
Resolved in #71
