### ISSUE TITLE
Id10t error?

### ISSUE THREAD

**Issue by bekirk** [ocmdev/rita#3]
I am sure I am doing something wrong.  Your instructions are great now.  But where do I go for help after I have everything installed?

I tried running this :
`[bin]$ ./rita import
INFO[0000] Starting run                                  start_time=2016-10-06 22:55:41
ERRO[0000] aborting file parsing for this file           error=Did not find a match in directory map file=/usr/local/bro/logs/2016-10-06/app_stats.22:04:24-22:53:38.log
ERRO[0000] aborting file parsing for this file           error=Did not find a match in directory map file=/usr/local/bro/logs/2016-10-06/communication.21:49:24-22:00:00.log
ERRO[0000] aborting file parsing for this file           error=Did not find a match in directory map file=/usr/local/bro/logs/2016-10-06/conn-summary.21:49:29-22:00:00.log
ERRO[0000] aborting file parsing for this file           error=Did not find a match in directory map file=/usr/local/bro/logs/2016-10-06/conn-summary.22:00:00-22:53:38.log
ERRO[0000] aborting file parsing for this file           error=Did not find a match in directory map file=/usr/local/bro/logs/2016-10-06/conn.21:49:29-22:00:00.log
`

It first was compressed bro files, but I uncompressed them to see if I got something different.

Any video tutorials, besides John's old one?

Thank you,
Brian

**Comment by lawrencehoffman** [comment]
For the majority of bro log types you'll get an abort as they're not supported by the analysis system yet. Essentially analysis is the purpose of the system, so we don't slurp up logs that won't be analyzed. To that end, currently only the logs 'conn.log' 'http.log' and 'dns.log' will be imported. You can use a tool like robomongo to connect to the db and ensure that you've got the logs you expect in there.
