### ISSUE TITLE
Log parser fails to import files which contain more fields than standard bro logs.

### ISSUE THREAD

**Issue by Zalgo2462** [ocmdev/rita#40]
When a bro log contains extra fields, the parser crashes with
```
ERRO[0000] the log contains a field with no candidate in the data structure  error="unmatched field in log" missing_field="FIELD" path=conn.log 
```
Extra fields may present themselves when users run additional bro scripts through bro such as:
```
redef record Conn::Info += {
  orig_cc: string &optional &log;
  resp_cc: string &optional &log;
};

event connection_state_remove(c: connection)
  {
    local orig_loc = lookup_location(c$id$orig_h);
    if ( orig_loc?$country_code )
      c$conn$orig_cc = orig_loc$country_code;
    local resp_loc = lookup_location(c$id$resp_h);
    if ( resp_loc?$country_code )
      c$conn$resp_cc = resp_loc$country_code;
  }
```
This happens because https://github.com/ocmdev/rita/blob/master/parser/parser.go#L379 enforces more restrictions than necessary while parsing. Having enough fields to fill the struct should be sufficient. Extra data should not cause a crash.

**Comment by ethack** [comment]
@Zalgo2462 Does your pull request (#41) completely resolve this so we can close the issue?

**Comment by Zalgo2462** [comment]
Yes.
