### ISSUE TITLE
Panic Error when executing show-beacons

### ISSUE THREAD

**Issue by troyim** [ocmdev/rita#43]
Not sure what is causing this error, everything else worked up until this point.  Any help would be appreciated.

Rita1:~/go/bin$ ./rita show-beacons -d beacons
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5aa53a]

goroutine 1 [running]:
panic(0x8798e0, 0xc4200100f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/mgo%2ev2.(*Iter).Next(0x0, 0x83ac60, 0xc420062b80, 0x83ac60)
	/home/XXXX/go/src/gopkg.in/mgo.v2/session.go:3684 +0x3a
gopkg.in/mgo%2ev2.(*Iter).All(0x0, 0x836ea0, 0xc4201301a0, 0x0, 0x7)
	/home/XXXX/go/src/gopkg.in/mgo.v2/session.go:3800 +0x27f
github.com/ocmdev/rita/commands.showBeacons(0xc4200852c0, 0x0, 0xc4200852c0)
	/home/XXXX/go/src/github.com/ocmdev/rita/commands/show-beacons.go:48 +0x22a
github.com/urfave/cli.HandleAction(0x863360, 0x938ed8, 0xc4200852c0, 0xc420054900, 0x0)
	/home/XXXX/go/src/github.com/urfave/cli/app.go:485 +0xd4
github.com/urfave/cli.Command.Run(0x8fae36, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x908ca2, 0x28, 0x0, ...)
	/home/XXXX/go/src/github.com/urfave/cli/command.go:207 +0xb96
github.com/urfave/cli.(*App).Run(0xc42007f380, 0xc42000c340, 0x4, 0x4, 0x0, 0x0)
	/home/XXXX/go/src/github.com/urfave/cli/app.go:250 +0x812
main.main()
	/home/XXXX/go/src/github.com/ocmdev/rita/rita.go:26 +0xf0

**Comment by Zalgo2462** [comment]
Hello, thank you for the bug report!
Could you please let us know what is in the beacons collection in Mongo?
Instructions:
* `mongo`
* `use beacons` (the name of your dataset)
* `db.beacon.find()`

The bug is in the client library for Mongo, we are probably handing it bad data.
Thanks in advance!

**Comment by troyim** [comment]
This is what I get when I type those commands.

> use beacons
switched to db beacons
> db.beacon.find()
>

**Comment by Zalgo2462** [comment]
Thanks. Next, can you run `./rita -version`

**Comment by troyim** [comment]
troylemaire@Unbunt-Rita1:~/go/bin$ ./rita -version
rita version v1.0.0-alpha-2-ge94657e

**Comment by Zalgo2462** [comment]
Alright. I think I've got this pinned down. I suspect that the "beacons" database doesn't exist. We need to implement a better error message. 
Type 'rita show-databases' and check to see that 'beacons' pops up.

**Comment by troyim** [comment]
Ok, I will try that on Monday when I get back to the office.

Thanks for your help!!

**Comment by troyim** [comment]
Ok, I had named the database test.  When I ran it again and used beacons as the database name, it worked correctly.  Thank you for the assistance.
