### ISSUE TITLE
Seg Fault in beaconing analysis

### ISSUE THREAD

**Issue by joelillo** [ocmdev/rita#47]
Line in util.go causes seg fault when list is empty:
[last := sortedIn[0]](https://github.com/ocmdev/rita/blob/master/util/util.go#L328)

Traced back to "newInput" variable containing an empty timestamp list:
[Code](https://github.com/ocmdev/rita/blob/master/analysis/beacon/beacon.go#L199)

**Comment by ethack** [comment]
Is this related to the suspected mongo query timeout for the first/last timestamp?  Should I create a separate issue for that or is this the root issue?

**Comment by Zalgo2462** [comment]
https://github.com/ocmdev/rita/blob/3d77b57af9c2756cee34fdf37358e7abe1385493/analysis/beacon/beacon.go#L191

Seems to imply that the query returned no results. The problem dataset will be needed in order to debug this issue.

**Comment by ethack** [comment]
@joelillo Do you still have the dataset that did this or have you seen it again anywhere?  In other words, do you know how to reproduce the issue?
