### ISSUE TITLE
Analysis hook

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#49]
Allow hooking into the analysis command to run custom commands afterwards.

Option 1 - Config file option:
* Create a new option in the configuration file that allows specifying a shell script
* Modify the backend so that after the analysis command finishes it reads the config option and executes the script

Option 2 - Command line switch:
* Add a new command line switch & argument to the analysis command that allows specifying a shell script via command line
* Modify the backend so that after the analysis command finishes it executes the command line argument

Option 3 - Log file watcher:
* Ensure that there is a log file entry that corresponds to a successful analysis run.
* The next step would be to have a separate service that triggers when it detects the log entry.  This wouldn't involve Rita source modification. 

This feature is to support post processing of the analysis data.  E.g. A script that uploads the analysis data to an off-site Mongo instance.  This is useful for frontend deployments, but could also be utilized for alerting.

**Comment by Zalgo2462** [comment]
What kind of script are you looking to run here? Could this be accomplished by scripting directly against the mongo backend?

**Comment by ethack** [comment]
I'm thinking a shell script as that would give the most flexibility and only require Rita to kick off one command.

I'm not sure what you mean by scripting against mongo.  In my mind what the script does after it's called is irrelevant since Rita just has to launch it.  But if you're thinking about having mongo trigger the script instead of Rita based on some conditions, I did look into that and there didn't seem to be a good solution.  The "accepted" solution was to use the fact that mongo can cluster and then tail a special event log that mongo creates when it is part of a cluster.  I'd say using Rita is less complex after seeing that option.

**Comment by ethack** [comment]
Closing based on prior discussion.

The script will be standalone that can be run manually or it can easily be configured to run automatically after a rita analysis if using something like cron.  So no analysis hook is needed.

We will just need to document the process so that users don't wonder why their data is not showing up in the frontend if they forget to run this.  But that's a non-issue at the moment.

BTW, thank you @Zalgo2462 for bringing in another point of view on this issue.  It was very helpful.
