### ISSUE TITLE
Fix Mongo query timeout in beaconing portion of analysis

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#50]
The query to get the first/last timestamps is probably timing out and causing there to be 0 beaconing results.

The following log output is characteristic of this issue.
```
[-] Running beacon analysis
INFO[3779] Building collection: beacon                  
INFO[3779] Running beacon hunt                          
DEBU[3779] Looking for first connection timestamp       
DEBU[3839] Looking for last connection timestamp        
DEBU[3839] First and last timestamps found               first=0 last=0 time_elapsed=1m0.000551352s
```

**Comment by Zalgo2462** [comment]
I'll check if the index is being properly created. 1 minute is unacceptable for an indexed lookup. 

https://github.com/ocmdev/rita/blob/3d77b57af9c2756cee34fdf37358e7abe1385493/analysis/beacon/beacon.go#L116

**Comment by Zalgo2462** [comment]
An index is not being placed on time. https://github.com/ocmdev/rita/blob/3d77b57af9c2756cee34fdf37358e7abe1385493/database/logcollections.go#L11

This can be easily fixed.

**Comment by Zalgo2462** [comment]
Can you try running the code here: https://github.com/Zalgo2462/rita/tree/conn-ts-index
(the conn-ts-branch on my repo)

**Comment by ethack** [comment]
The person with this issue ran the new code and there were still no beacon results.  I think we'll have to wait until we can obtain a dataset ourselves that has this problem in order to debug.

**Comment by ethack** [comment]
@Zalgo2462 I believe this is the same issue we discussed earlier today, but just needs to be merged into dev.

Based on the feedback we received, however, it doesn't seem like this fixed the particular user's issue.  Still a good thing to add in.

**Comment by ethack** [comment]
@Zalgo2462 I think we can close this one out, yes?  I don't think there are more ideas to try and the dataset that reproduces this is unavailable.
