### ISSUE TITLE
Implement Mongo bulk insert for data import

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#51]
The current implementation of the import feature uses individual Mongo insert commands for each data point that goes into the database.  This area is highly threaded, but it is worth researching using bulk inserts instead.

The current proposal that would require the least messing with the current threading code (a large undertaking) is to add in a buffer of some sort that sits between the import code and the Mongo database.  Instead of inserting directly into Mongo, the threads would place the data into an in-memory buffer.  When the buffer is full, additional code will take that data and perform a bulk insert into Mongo.

**Comment by Zalgo2462** [comment]
Neat enough, it looks like we can just pull more out of the channel and write in bulk. Golang is awesome.

https://github.com/ocmdev/rita/blob/3d77b57af9c2756cee34fdf37358e7abe1385493/parser/docwriter.go#L86

**Comment by ethack** [comment]
Bumping up the priority because if this produces a speed improvement, it would have benefits for our hunt team service offering.

**Comment by strandjs** [comment]
Agreed.  This is a gating issue because on some hunts it is taking days on just the import.

**Comment by JonZeolla** [comment]
I similarly hit a scenario where initial import took over a week just for one day of bro logs.  Running on my personal server, 64GB of RAM, 2 CPU, etc.  Very interested in this feature.

**Comment by Zalgo2462** [comment]
Could you please take this branch of the code out for a test drive and put it through its paces @anyone.

https://github.com/Zalgo2462/rita/tree/new-parser

Thanks!

**Comment by JonZeolla** [comment]
I'll try to spin it up this week

**Comment by JonZeolla** [comment]
How do you want me to provide feedback?  If you want to throw up a PR and I can review it in there.  I'm working on this now, only found 1 minor thing so far.

**Comment by Zalgo2462** [comment]
If you have thoughts on the actual code, I can put up a PR. If not, please post your thoughts here. I'm excited to hear the feedback! Thanks

**Comment by JonZeolla** [comment]
I've just found that it's a somewhat easier back-and-forth using PRs to provide feedback.  If you'd prefer, I can just provide feedback here.

I'm still early in the review process but by default `rita` is not in your `$PATH`, as the README claims.

**Comment by JonZeolla** [comment]
The `mongod` service also needs to be started before you run the `rita import`.

**Comment by JonZeolla** [comment]
I was able to import ~70,000,000 lines of conn, dns, and http logs (roughly 1 hour of logs) in 88 minutes on a system with 8 vCPUs and 64GB of RAM.  I don't have a baseline to compare it against because the last time I did this I was doing 1 day of logs and it took well over a week to process, but because the dataset couldn't fit in memory I get the feeling there were other reasons why it was so slow.

Running `rita analyze` now and I'll do some playing around after it's done.  All good so far, except for my prior 2 comments.

**Comment by Zalgo2462** [comment]
Thanks, what was the size in MB of the logs?

**Comment by JonZeolla** [comment]
*sigh* I accidentally cut the power to the VM this morning when working on something else, so it's unhappy with me.  Working to fix...

To answer your question, I'm currently doing ~6200MB of Conn, ~4300MB of DNS, and ~3500MB of HTTP (one file each, so no overhead with column headers, etc.).  Soon I am going to look at analyzing a larger batch of logs, maybe 50GB or so, and see how it handles it.  Like I mentioned earlier, it's hard to diff your changes against master in this format - would you mind pointing me to the bulk insert changes, and any related params/consts?

**Comment by Zalgo2462** [comment]
INFO[0000] Finished collecting log file details          current_time="2017-05-22 15:21:01"
INFO[1414] Finished parsing file                         path="/share/bro1/2016-06-20/conn.00:00:00-00:00:00.log.gz"
INFO[2120] Finished parsing file                         path="/share/bro1/2016-06-20/http.00:00:00-00:00:00.log.gz"
INFO[3403] Finished parsing log files                    current_time="2017-05-22 16:17:44" total_time=56m43.512958478s
Finished importing!

655M -rw-r--r--. 1 - - 655M Jun 20  2016 conn.00:00:00-00:00:00.log.gz
2.6G -rw-r--r--. 1 - - 2.6G Jun 20  2016 http.00:00:00-00:00:00.log.gz

So, ~3 gigs in 56 minutes. A good 15-30 minutes of that was indexing. I'm going to run this dataset with the old parser to get a before and after.
