### ISSUE TITLE
Dockerize Rita

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#68]
To facilitate easier testing and evaluate performance for production deployments.

Current brainstormed options:
* Add docker files to current rita repo.
* Create new repo under ocmdev for files to live.
* Deploy on [Docker Hub](https://hub.docker.com/)

Also, create a readme or add to the readme pointing to the right place and giving the command(s) that sets everything up.

**Comment by Zalgo2462** [comment]
```
FROM golang:1.8-alpine
RUN apk update && apk upgrade && apk add --no-cache git && apk add --no-cache make
RUN mkdir /logs
RUN mkdir $HOME/.rita/
WORKDIR /go/src/rita
COPY . .
RUN make install
ENTRYPOINT ["go-wrapper", "run"]
```
Is enough to dockerize rita assuming you make two mounts. 
This requires you to mount your bro logs to /logs and your rita configuration to /root/.rita/config.yaml.

So if you copy the Dockerfile to your source directory,
`docker build -t rita .`
`docker run -it --rm -v /path/to/bro/logs:/logs/:ro -v /path/to/rita/config.yaml:/root/.rita/config.yaml:ro rita import`

You may want to create an alias.
`alias rita="docker run -it --rm -v /path/to/bro/logs:/logs/:ro -v /path/to/rita/config.yaml:/root/.rita/config.yaml:ro rita"`

**Comment by ethack** [comment]
That will pull Rita from the github master branch.  That may have been your intention, but if you do it the following way it will work off whatever code is in your current directory.  That lets you work off other branches by using your normal git commands on your host system first.
```
FROM golang:1.8-alpine
RUN apk update && apk upgrade && apk add --no-cache git && apk add --no-cache make
RUN mkdir /logs
RUN mkdir $HOME/.rita/
RUN mkdir -p /go/src/github.com/ocmdev/rita
WORKDIR /go/src/github.com/ocmdev/rita
COPY . .
RUN make install
ENTRYPOINT ["go-wrapper", "run"]
```

**Comment by Zalgo2462** [comment]
What I have up above will actually work with any branch of the Rita code. You just need to place the docker file in your host's copy of the source code. Note the host copy doesn't even need to be in the GOPATH. If you want to run dev in docker, simply check out dev before you docker build.

**Comment by ethack** [comment]
I was in the dev branch and it was running the master branch build of rita.

When I switched the Dockerfile over it was giving me the dev branch (from my current directory).

**Comment by Zalgo2462** [comment]
Well that's odd. Your version tag claims to be the latest commit on the dev branch, but the commands don't sync up. I see what's causing it and indeed your suggestion should fix it. Giving it a try now
