### ISSUE TITLE
Include Duration in Beaconing Analysis

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#72]

**Comment by ethack** [comment]
@Zalgo2462 I think this issue was from our discussions in the office. However, I don't have any details on what this actually means.  Do you have any insight?

**Comment by Zalgo2462** [comment]
This issue is with regards to the regularity of the durations of the connections. This is not ts_duration. Right now beaconing primarily operates on the regularity of the durations between connections. This would take into account the regularity of the durations of the connections themselves.

**Comment by ethack** [comment]
Current opinions are that analyzing data size consistency between packets/connections is a better metric than this would be.
